export const START_FETCH = "START_FETCH";
export const SUCCESS_FETCH = "SUCCESS_FETCH";
export const ERROR_FETCH = "ERROR_FETCH";
export const END_FETCH = "END_FETCH";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_END = "AUTH_END";

export const CLEAN_UP = "CLEAN_UP";

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_ERROR = "VERIFY_ERROR";
export const VERIFY_END = "VERIFY_END";

export const RECOVER_START = "RECOVER_START";
export const RECOVER_SUCCESS = "RECOVER_SUCCESS";
export const RECOVER_ERROR = "RECOVER_ERROR";
export const RECOVER_END = "RECOVER_END";

export const PROFILE_UPDATE_START = "PROFILE_UPDATE_START";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";
export const PROFILE_UPDATE_END = "PROFILE_UPDATE_END";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER_END = "DELETE_USER_END";
